on:
  pull_request:
    branches:    
      - master
  push:
    branches:    
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ['darwin', 'linux', 'windows']
        goarch: ['amd64']
    name: Building for ${{ matrix.goos }}_${{ matrix.goarch }}
    env:
      GOOS: "${{ matrix.goos }}"
      GOARCH: "${{ matrix.goarch }}"
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - uses: actions/cache@v3
        with:
          # In order:
          # - Module download cache
          # - Build cache (Linux)
          # - Build cache (Mac)
          # - Build cache (Windows)
          path: |-
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ matrix.goos }}-${{ matrix.goarch }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |-
            ${{ matrix.goos }}-${{ matrix.goarch }}-
      - name: Set bin_name output
        id: bin_name
        run: |-
          bin_name="k8s-charter_${GOOS}_${GOARCH}"
          if [[ "${GOOS}" == "windows" ]]; then
            bin_name+=".exe"
          fi
          echo "::set-output name=value::${bin_name}"
      - name: Build binary
        run: |-
          CGO_ENABLED=0 go build -ldflags "-s -w" -o "${{ steps.bin_name.outputs.value }}"
          ls "${{ steps.bin_name.outputs.value }}"
      - name: Create release and upload asset to latest release
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: latest
          files: |-
            ${{ steps.bin_name.outputs.value }}_latest
      - name: Extract tag value if tag release
        if: startsWith(github.ref, 'refs/tags/')
        id: tag
        run: echo ::set-output name=value::${GITHUB_REF/refs\/tags\//}
      - name: Create release and upload asset to tag release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ steps.tag.outputs.value }}
          name: ${{ steps.tag.outputs.value }}
          files: |-
            ${{ steps.bin_name.outputs.value }}_${{ steps.tag.outputs.value }}
